apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
 name: go-cicd-demo
description: main application pipeline
serialPipeline:
 stages:
 - targetId: run-cr-dev
   profiles: [dev]
 - targetId: run-cr-prd
   profiles: [prod]
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: run-cr-dev
description: Cloud Run development service
run:
 location: projects/meta-yen-311209/locations/europe-west2
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: run-cr-prd
description: Cloud Run production service
run:
 location: projects/meta-yen-311209/locations/europe-west2