apiVersion: skaffold/v3alpha1
kind: Config
metadata: 
  name: deploy-run-go-cicd
profiles:
- name: dev
  manifests:
    rawYaml:
    - run-dev.yaml
- name: prod
  manifests:
    rawYaml:
    - run-prod.yaml
- name: prod-new-region
  manifests:
    rawYaml:
    - run-prod.yaml
deploy:
  cloudrun: {}